# Facts about numpy
- Every element in a NumPy array uniformly occupies n bytes.
- NumPy arrays are stored contiguously in memory.
- 

In [3]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

## 1. allclose() function
- A comparison function that checks whether two arrays are equal or pretty similar. 
- Compares two arrays of the data item by elementwise within a threshold.
- Then returns a Boolean value as a result.

In [40]:
a = np.array([0.16,0.26,0.365])
b = np.array([0.15,0.25,0.36])
tolerance1 = 0.1
tolerance2 = 0.05
print(np.allclose(a,b,tolerance1))
print(np.allclose(a,b,tolerance2))

True
False


## 2. where() function
- Where() is a function that returns elements from an array that meets a set of criteria.

In [41]:
list1 = np.array([1,4,7,6,1,7,3,8,9])
# Where the elements in list1 are less than 7, returns the index position
np.where(list1<7)

(array([0, 1, 3, 4, 6]),)

## 3. extract() function
- Extract() is used to retrieve specific members with an array depending on criteria.

In [43]:
array_test = np.random.randint(18, size=12)
array_test

array([ 5, 12,  8,  4,  1,  3,  4,  0, 17, 10,  2, 16])

In [44]:
cond = np.mod(array_test, 2)==1
cond

array([ True, False, False, False,  True,  True, False, False,  True,
       False, False, False])

In [45]:
np.extract(cond, array_test)

array([ 5,  1,  3, 17])

## 4. einsum() function
- The einsum() function in NumPy (short for "Einstein summation") allows for advanced indexing and summation of multi-dimensional arrays.

In [46]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a_diag = np.einsum('ii->i', a)
print("option1\n",a_diag)
print('option2\n',np.einsum(a,[0,0],[0]))

option1
 [1 5 9]
option2
 [1 5 9]


In [47]:
a_transpose = np.einsum("ij->ji",a)
print("option1\n",a_transpose)
print("option2\n",np.einsum(a,[1,0]))

option1
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
option2
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## 6. clip() function
- The clip() function in NumPy is a method for limiting the values in an array to a specified range.

In [48]:
x = np.array([3, 4, 12, 20, 2, 2, 3, 7, 1, 2, 12, 0])
print(np.clip(x,2,5))

[3 4 5 5 2 2 3 5 2 2 5 2]


### 1)Slice first 3 elements

In [15]:
x = np.asarray(range(1,26), np.int8).reshape(5,5)
print(x)
as_strided(x, shape=(3,), strides=(1,))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([1, 2, 3], dtype=int8)

###  2)Slice first 13 elements

In [8]:
as_strided(x, shape=(13,), strides=(1,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13], dtype=int8)

### 3)Flatten a 2D array

In [17]:
as_strided(x, shape=(25,), strides=(2,))

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
       115, 101,  47,  48,   0,   0,   0,  49,   0,   0,   0, -80],
      dtype=int8)

In [13]:
# You can also try like
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25], dtype=int8)

### 4) Skip every other element

In [18]:
print(x)
as_strided(x, shape=(3,), strides=(2,))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([1, 3, 5], dtype=int8)

In [19]:
# You can also try like
x[0,::2]

array([1, 3, 5], dtype=int8)

### 5) Slice first column

In [27]:
x[:5,0] # 0 is column number here

array([ 1,  6, 11, 16, 21], dtype=int8)

### 6) Slice a diagonal

In [28]:
x.diagonal()

array([ 1,  7, 13, 19, 25], dtype=int8)

### 7) Repeat the first element

In [29]:
np.broadcast_to(x[0,0], (5,))

array([1, 1, 1, 1, 1], dtype=int8)

### 8) Simple 2D slicing

In [30]:
x[:3,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]], dtype=int8)

### 9) Sparse slicing

In [37]:
print(x)
print("\nsparce sclicing\n",x[::2,::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

sparce sclicing
 [[ 1  3  5]
 [11 13 15]
 [21 23 25]]


### 10) Transpose a 2D array

In [39]:
print(x[:3,:3])
print("\n Transposed version\n",x[:3,:3].T)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]

 Transposed version
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]]
